// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)

import ConfirmationController from "./confirmation_controller"
application.register("confirmation", ConfirmationController)

import CopyToClipboardController from "./copy_to_clipboard_controller"
application.register("copy-to-clipboard", CopyToClipboardController)

import ElementController from "./element_controller"
application.register("element", ElementController)

import SearchParamsController from "./search_params_controller"
application.register("search-params", SearchParamsController)
